apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sample-com
  namespace: dev
spec:
  secretName: sample-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - sample.com
  - '*.sample.com'